using System.Drawing;
using System.Drawing.Drawing2D;

namespace SonyTray.Services;

/// <summary>
/// Draws the Sony Tray runtime tray icon: the same visual language as the app
/// icon (Assets/app.ico, generated by tooling/make-icon.ps1 — a blue rounded-square
/// gradient badge with a white headphone glyph), scaled to 32x32, plus a
/// connection-status dot bottom-right (LimeGreen when connected, Gray otherwise)
/// ringed in white so it stays legible against the badge.
/// </summary>
public static class TrayIconFactory
{
    public static Icon Create(bool connected)
    {
        const int size = 32;
        using var bmp = new Bitmap(size, size);
        using (var g = Graphics.FromImage(bmp))
        {
            g.SmoothingMode = SmoothingMode.AntiAlias;
            g.Clear(Color.Transparent);

            // Rounded-square gradient badge (#1976D2 -> #0D47A1, vertical)
            using (var badge = RoundedRect(0, 0, size, size, 7))
            using (var badgeBrush = new LinearGradientBrush(
                new RectangleF(0, 0, size, size),
                ColorTranslator.FromHtml("#1976D2"),
                ColorTranslator.FromHtml("#0D47A1"),
                LinearGradientMode.Vertical))
            {
                g.FillPath(badgeBrush, badge);
            }

            // White headphone headband (arc, round caps)
            using (var band = new Pen(Color.White, 2.75f) { StartCap = LineCap.Round, EndCap = LineCap.Round })
            {
                g.DrawArc(band, 6f, 6.5f, 20f, 15f, 180, 180);
            }

            // White ear cups, mirrored left/right
            using (var earBrush = new SolidBrush(Color.White))
            using (var leftCup = RoundedRect(5f, 17.5f, 6.5f, 9.5f, 2.25f))
            using (var rightCup = RoundedRect(size - 5f - 6.5f, 17.5f, 6.5f, 9.5f, 2.25f))
            {
                g.FillPath(earBrush, leftCup);
                g.FillPath(earBrush, rightCup);
            }

            // Status dot, bottom-right, ~9px, with a 1px white ring
            const float dotSize = 9f;
            const float dotMargin = 1f;
            float dotX = size - dotSize - dotMargin;
            float dotY = size - dotSize - dotMargin;
            using (var ring = new SolidBrush(Color.White))
            {
                g.FillEllipse(ring, dotX - 1f, dotY - 1f, dotSize + 2f, dotSize + 2f);
            }
            using (var dot = new SolidBrush(connected ? Color.LimeGreen : Color.Gray))
            {
                g.FillEllipse(dot, dotX, dotY, dotSize, dotSize);
            }
        }
        nint h = bmp.GetHicon();
        try { return (Icon)Icon.FromHandle(h).Clone(); }
        finally { DestroyIcon(h); }
    }

    private static GraphicsPath RoundedRect(float x, float y, float width, float height, float radius)
    {
        var path = new GraphicsPath();
        float d = radius * 2f;
        path.AddArc(x, y, d, d, 180, 90);
        path.AddArc(x + width - d, y, d, d, 270, 90);
        path.AddArc(x + width - d, y + height - d, d, d, 0, 90);
        path.AddArc(x, y + height - d, d, d, 90, 90);
        path.CloseFigure();
        return path;
    }

    [System.Runtime.InteropServices.DllImport("user32.dll")]
    private static extern bool DestroyIcon(nint handle);
}
